### ISSUE TITLE
pdf-rapport opslaan in repo?

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/moneos#4]
@joost-vanoverbeke Ik zie het volledige rapport in de repo staan onder `150_geintegreerd_rapport/_book`, en ik vroeg me af of het wel een goed idee is om hier regelmatig een update van te gaan publiceren (is combinatie van tekst en binary file).  Moest je het niet onder Gdrive opslaan, dan zou het me nog wel zinvol lijken dat niet iedereen het opnieuw moet bouwen, maar vermits iedereen het rapport ook op Gdrive kan raadplegen, lijkt me dit overbodig en kan je mss de map `_book` beter opnemen in `.gitignore`?  Om over na te denken...

**Comment by joost-vanoverbeke** [comment]
in .gitignore is al opgenomen dat .pdf files worden genegeerd. Die _book folder kan daar ook wel bij ingezet worden.

**Comment by ElsLommelen** [comment]
Ah, sorry, het was me ontgaan dat die pdf niet meegekomen was met mijn pull (maar er nog stond).
Ik zou ook _bookdown.yml kunnen aanpassen zodat die pdf gewoon in de map `150_geintegreerd_rapport` wordt opgeslagen, niet in een submap, dat is misschien gemakkelijker?  Of nadat ik een alternatief uitgewerkt heb voor dat path, hopelijk rechtstreeks in Gdrive...  Laat dus voorlopig maar zitten om die map te negeren.
