### ISSUE TITLE
nieuwe comments detecteren in review proces

### ISSUE THREAD

**Issue by joost-vanoverbeke** [inbo/moneos#7]
@ElsLommelen als je ergens een nieuwe comment hebt toegevoegd, zie ik daar een e-mail van verschijnen (ik heb trouwens kunnen instellen dat alle info van de inbo repo naar mijn inbo mail adres wordt gestuurd :) ). Maar in de pull requests window op github zie ik niet hoe je nieuwe commentaren makkelijk kan opsporen. Ik moet altijd alles doorscrollen om te zien waar de nieuwe commentaren staan. Is er geen makkelijker manier die aangeeft waar er nieuwe comments zijn toegevoegd?

**Comment by joost-vanoverbeke** [comment]
ik zie nu wel dat locatie in de titel van de mails staat :)

**Comment by joost-vanoverbeke** [comment]
toch niet helemaal, nog altijd zoeken waar de nieuwe commentaar precies staat ...

**Comment by ElsLommelen** [comment]
Onderaan de email staat 'Reply to this email directly, `view it on GitHub`, or `unsubscribe`.  (Dit wordt door google nogal eens als handtekening aanzien en verborgen achter de 3 puntjes.)
Als je op die `view it on GitHub` klikt, kom je direct bij de nieuwe commentaar uit.  (Ook zijn nieuwe commentaren vaak eventjes geel gekleurd in Github als je toevallig in die PR aan 't kijken was op het moment dat die commentaar toegevoegd wordt.)
